name: PR CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE'
  workflow_dispatch:

concurrency:
  group: pr-ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    permissions:
      contents: read
      checks: write
      pull-requests: write
    uses: ./.github/workflows/ci.yml
