on:
  push:
    branches:
      - 'develop'
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'

name: Publish

jobs:
  upcoming_version:
    runs-on: ubuntu-latest
    container: tartar4s/semver-ci:v0.5.0-dev.a3783039
    outputs:
      UPCOMING_VERSION: ${{ steps.set_upcoming_version.outputs.UPCOMING_VERSION }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set upcoming version
        id: set_upcoming_version
        run: |
          git config --global --add safe.directory .
          export SCOPE=$(svci scope)
          echo "UPCOMING_VERSION=$(svci version)" >> "$GITHUB_OUTPUT"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: tartar4s/semver-ci

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./debug.Dockerfile
          push: true
          tags: ${{needs.upcoming_version.outputs.UPCOMING_VERSION}}
          labels: ${{ steps.meta.outputs.labels }}
  tag:
    runs-on: ubuntu-latest
    container: tartar4s/semver-ci:v0.5.0-dev.a3783039
    if: startsWith(github.ref_name, 'release/') || startsWith(github.ref_name, 'hotfix/')
    needs: [ upcoming_version, build ]
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Tag
        run: |
          git config --global --add safe.directory .
          svci tag "$TAG_NAME"
    env:
      TAG_NAME: ${{needs.upcoming_version.outputs.UPCOMING_VERSION}}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
